name: CMakeProject1

on:
  push:
    branches: [ "main" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      working-directory: ${{github.workspace}}
      run: |
        cmake -S . -B out/build `
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} `
      shell: pwsh

    - name: Build
      run: cmake --build ${{github.workspace}}/out/build --config ${{env.BUILD_TYPE}}

    - name: Run
      working-directory: ${{github.workspace}}/out/build/${{env.BUILD_TYPE}}
      run: |
        start /b .\CMakeProject1.exe
        timeout /t 5
        taskkill /f /im CMakeProject1.exe
      shell: cmd
